### ISSUE TITLE
Openshift.getEvents() fails

### ISSUE THREAD

**Issue by mocenas** [xtf-cz/xtf#361]
Update to fabric 4.10.1 in PR[360](https://github.com/xtf-cz/xtf/pull/360) seems to break getting events from OCP.
Code `openShift.getEvents()` ends with:
`
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.perf2.xpaas:8443/apis/events.k8s.io/v1beta1/namespaces/mocenas/events. Message: events.events.k8s.io is forbidden: User "xpaasqe" cannot list events.events.k8s.io in the namespace "mocenas": no RBAC policy matched. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=events.k8s.io, kind=events, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=events.events.k8s.io is forbidden: User "xpaasqe" cannot list events.events.k8s.io in the namespace "mocenas": no RBAC policy matched, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
`
Tested against OCP 3.11 and 4.4.4

**Comment by mocenas** [comment]
FYI @Crumby @mnovak1

**Comment by simkam** [comment]
isn't it https://github.com/fabric8io/kubernetes-client/issues/2205? It should be fixed in 4.10.2

**Comment by mocenas** [comment]
@simkam Seems it can be it. With the update to 4.10.1 also all openshift event references were changed from:

**Comment by mnovak1** [comment]
Ok, what about to revert 4.10.1-> 4.7.1 and wait for the new version? fyi @Crumby

**Comment by Crumby** [comment]
@mocenas Version change is only commit since 0.16 release. You can use that one till f8 10.1.2 is out. We can revert if more is coming into the code and new version still isn't out. Optionally try downgrade to 4.9.2...

**Comment by mocenas** [comment]
@Crumby I don't have problem in our production testSuite, we are on 0.16. I encountered this during MR [359](https://github.com/xtf-cz/xtf/pull/359) - this problem entirely broke the MR.

**Comment by istraka** [comment]
@Crumby I `4.9.2` does not change event API. I will submit downgrade PR.
